### ISSUE TITLE
Assessment 2

### ISSUE THREAD

**Issue by rizzamandasari** [faisalabdulr/6706220090_ASSESSMENT2#1]
Aplikasi berjalan baik, namun ada beebrapa hal yang perlu diperbaiki atau ditambahakan
1. Fitur-Fitur Assessment 1 jadi hilang, spt dual bahasa image dll.
2. FAB masih overlap dengan list
3. Harga mmg sengaja diset desimal? 
Perbaikan dapat disubmit sebelum tanggal 25 Juni 2024

**Comment by faisalabdulr** [comment]
perbaikan Assement 2 link drive : https://drive.google.com/drive/folders/1A1YNRlqT0NA5fx3g57IW_5NsmnGt3FqS?usp=sharing

**Comment by rizzamandasari** [comment]
OK. Close
